extends: eslint:recommended
env:
  browser: true
  es2021: true
  node: true
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  prefer-const: warn
  no-var: warn
  object-curly-spacing:
    - warn
    - always
